### ISSUE TITLE
请问Table 2中是使用什么基准模型进行比较的

### ISSUE THREAD

**Issue by 4real3000** [IronBeliever/CaR#3]
![WX20240408-145451@2x](https://github.com/IronBeliever/CaR/assets/145254475/ecfe1960-105f-49e5-9266-90aede331511)
请问在表2中是使用什么模型和Alpaca-PandaLM、Alpaca-cleaned、Vicuna、Alpaca、Alpagasus、AlpaCaR这几个模型进行对比产生WS、WR、QS这三个结果的。
您的文章对我很有帮助，期待您的回复，谢谢！

**Comment by IronBeliever** [comment]
感谢您对这篇工作的关注！

主实验部分的baseline使用的是数据集的reference response。\
我们也注意到论文确实没有说明这一点，即将在新的版本中修正😀

**Comment by dongjiancheng77** [comment]
请问pandalm的reference response具体出处是哪里吗？paper中似乎没有

**Comment by IronBeliever** [comment]
[testset-v1.json](https://github.com/WeOpenML/PandaLM/blob/main/data/testset-v1.json)为pandalm_170的每条指令用若干个模型两两比较，用"idx"标识，[gpt-3.5-turbo-testset-v1.json](https://github.com/WeOpenML/PandaLM/blob/main/data/gpt-3.5-turbo-testset-v1.json)同标识的"gpt_reference"字段为gpt-3.5-turbo生成的reference response；结合两个文件，然后对指令去重即可
