### ISSUE TITLE
为什么选择得分小的

### ISSUE THREAD

**Issue by caowanxia123** [IronBeliever/CaR#4]
![图片1](https://github.com/IronBeliever/CaR/assets/50775765/9101702d-f958-4257-a8d9-7c273b57e3be)
得分按照从低到高排列
为什么选择得分较低的样本，不是得分越高越好吗

**Comment by IronBeliever** [comment]
是的，您指出了一个小bug！
我们在最后重新封装方法的时候弄错了这个细节
但实验过程中并没有犯这个错误
非常感谢🙏目前已经修正了这个错误

**Comment by caowanxia123** [comment]
非常感谢分享CaR方法，我最近将这个方法用在了一个中文大模型的微调上，直接用仓库中提供的在alpaca 3000多条数据上训练的rank模型到中文的指令微调数据上，挑选了原始模型约1/100的数据用于微调，和随机挑选的1/100数据相比，反而是随机筛选的更好（GPT4评分），请问您有遇到过类似情况吗，或者在英文alpaca上训练的模型能否迁移到非英文数据集

**Comment by IronBeliever** [comment]
我并没有遇到这种情况，实验都体现了筛选方法的有效性

但以下几个角度也许能解决问题：
- IQS模型确实没有考虑到中文的指令，虽然xlm-Roberta拥有多语言能力，但是我们的微调数据均为英语指令，可能导致了场景限制；或许您可以考虑*增加一个翻译模块*或者*标注少量中文数据*用相同的方法重训一个多语言IQS模型
- 虽然我们提到仅用约2%的指令获得好的模型表现，但不是单纯追求更少的指令；经验认为，指令的数量在200-1000左右可以让模型获得一个任务的能力，这也是超参数选择考虑到的一些原因；或许300条指令太少了，导致了一定的随机结果（指令数量太少时没有明显的规律）

**Comment by XingYu-Zhong** [comment]
请问原本的iqs的数据集是否有公开呢？

**Comment by IronBeliever** [comment]
IQS模型训练数据的原始版本可以在[这里下载](https://github.com/lunyiliu/CoachLM/blob/main/Expert%20Revision%20Dataset.json)
并删掉了修改前后距离较小的1211条指令（通过设置阈值）

**Comment by yuanjing-jane** [comment]
> IQS模型训练数据的原始版本可以在[这里下载](https://github.com/lunyiliu/CoachLM/blob/main/Expert%20Revision%20Dataset.json) 并删掉了修改前后距离较小的1211条指令（通过设置阈值）

1. 这个IQS原始数据集中共2300条数据，请问里面的 Revised Instruction， Revised Input， Revised Response，使用大模型修订/改写生成的，还是人工手动标注的？如果是用大模型修订得到，用的是哪个模型呢？
2. IQS数据都是从alpaca中抽取的标注，再用于训练IQS，然后再用其为alpaca全部数据进行评分排序，这样的IQS模型可以应用到其他数据集上吗，泛化性好吗？还是针对每个不同的数据集（比如 不同的垂直领域），都需要先标注一份IQS数据集用于训练IQS模型？
3. 为什么会选择用xlm-roberta，有实验其他模型吗，效果怎么样呢？

**Comment by IronBeliever** [comment]
1. Expert Revised数据集是译员手工修订的，具体可以看[这篇工作](https://github.com/lunyiliu/CoachLM)
2. 这篇论文主要针对通用领域的指令跟随能力，我们后续的实验表明这种方法在通用领域的数据集上具有不错的泛化性(Dolly, 或者Alpaca, Dolly_v2, Alpaca-evol-instruct, HC3, LIMA混合数据集上都有效)，但在gpt4生成的高质量数据上不起作用；所以感觉垂直领域应该也需要先标点数据训练模型
3. 这篇工作QE任务的启发，预训练模型等一开始都参考[Comet](https://aclanthology.org/2020.emnlp-main.213.pdf)，也没试其他模型；xlm-roberta有个小优势是有多语言能力，虽然我们没用上😂
