### ISSUE TITLE
可以分享一下绘图代码吗

### ISSUE THREAD

**Issue by pierowu** [IronBeliever/CaR#5]
您好！感谢您的工作，我觉得文章中的这张图画得很好，可否分享一下绘图代码，或者分享一下如何画出这种风格？
![image](https://github.com/user-attachments/assets/9f1f71f4-0693-474d-8b87-f3b9409f573c)

**Comment by IronBeliever** [comment]
感谢您的关注！您可以尝试使用draw.io“草图”风格。
